ten_san_pham_raw = input("tên sản phẩm: ")
so_luong_input = input("số lượng sản phâm: ")
so_luong_san_pham = int(so_luong_input)
don_gia_input = input("đơn giá sản phẩm: ")
don_gia_san_pham = float(don_gia_input)
tong_tien_hang = (so_luong_san_pham * don_gia_san_pham )
thue_VAT = (tong_tien_hang * 0.08)
tong_thanh_toan = (tong_tien_hang + thue_VAT)
print("========== HÓA ĐƠN BÁN HÀNG ==========")
print(f"tên sản phẩm            :{ten_san_pham_raw}")
print(f"số lượng sản phẩm      :{so_luong_input}")
print(f"đơn giá sản phẩm        :{don_gia_input}")
print(f"tổng tiền hàng       :{tong_tien_hang:,.0f}")
print(f"thuế VAT                :{thue_VAT:,.0f}")
print(f"tổng thanh toán          :{tong_thanh_toan:,.0f}")
