so_tien_goc  = float(input("nhap so tien goc: "))
lai_suat_nam = float(input("nhap lai suat nam: "))
thoi_gian    = float(input("nhap thoi gian: "))
tong_tien = so_tien_goc * (1 + lai_suat_nam * thoi_gian)
print("\n--- KẾT QUẢ TÍNH LÃI ĐƠN ---")
print(f"Số tiền gốc: {so_tien_goc:,.0f} VNĐ")
print(f"Lãi suất: {lai_suat_nam * 100}%/năm")
print(f"Thời gian gửi: {thoi_gian} năm")
print(f"Tổng số tiền nhận được: {tong_tien:,.0f} VNĐ")
